name: "Compute Supported Magento 2 Versions"
author: "Graycore"
description: "A Github Action that computes the Github Actions matrix for the currently supported versions of Magento 2"

outputs:
  matrix:
    description: "The Github Actions matrix of software technologies required to run Magento."
    value: ${{ steps.generate.outputs.matrix }}

runs:
  using: 'composite'
  steps:
  - run: |
      content=`cat ${{ github.action_path }}/supported.json | jq -c`
      echo "::set-output name=matrix::$content"
    shell: bash
    id: generate
    
branding:
  icon: "code"
  color: "green"
