name: "Compute Supported Magento 2 Versions"
author: "Graycore"
description: "A Github Action that computes the Github Actions matrix for the chosen versions of Magento 2"

inputs:
  kind:
    required: false
    description: "The kind of versions you want to return. Allowed values are `currently-supported, latest, custom`"
    default: "currently-supported"
  custom_versions:
    required: false
    description: "The specific custom versions of Magento that you want to use. Only applies when `kind` is `custom`"
    default: ""

outputs:
  matrix:
    description: "The Github Actions matrix of software technologies required to run Magento."
    value: ${{ steps.generate.outputs.matrix }}

runs:
  using: "node16"
  main: dist/index.js

branding:
  icon: "code"
  color: "green"
