name: "Compute Supported Versions"
author: "Graycore"
description: "A Github Action that computes a Github Actions matrix for the currently supported versions of Magento 2"

outputs:
  matrix:
    description: "The Github Actions matrix of software technologies required to run Magento."
    value: ${{ steps.generate.outputs.matrix }}

runs:
  using: 'composite'
  steps:
  - run: echo "::set-output name=matrix::'test'"
    shell: bash
    id: generate
  - run: echo ${{ steps.generate.outputs.matrix }}
    shell: bash
    
branding:
  icon: "code"
  color: "green"
