name: "Installation Test"
author: "Graycore"
description: " A Github Action that tests the installability of a Magento Package"

inputs:
  php_version: 
    required: true
    default: "8.1"
    description: "PHP Version to use"

  cache_key: 
    required: true
    default: "2"
    description: "The cache key used to hold Composer Packages"
  
  composer_version: 
    required: true
    default: "2"
    description: "The version of composer to use"

  use_local_source:
    required: false
    default: "true"
    description: "Whether or not you want to test your local package or not."

  source_folder:
    required: true
    default: $GITHUB_WORKSPACE
    description: "The source folder of the package"

  package_name:
    required: true
    description: "The name of the package"

  magento_directory:
    required: true
    default: "../magento2"
    description: "The folder where Magento will be installed"

  magento_version:
    required: true
    default: "magento/project-community-edition"
    description: "The version of Magento to test against"
    
  magento_repository:
    required: true
    default: "https://mirror.mage-os.org/"
    description: "Where to install Magento from"

  composer_cache_key:
    required: false
    default: ''
    description: A key to version the composer cache. Can be incremented if you need to bust the cache.
  
  composer_auth:
    required: false
    description: "Composer Authentication Credentials"

runs:
  using: "composite"
  steps:
    - uses: graycoreio/github-actions-magento2/setup-magento@main
      id: setup-magento
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v${{ inputs.composer_version }}
        mode: extension
        magento_version: ${{ inputs.magento_version }}

    - uses: graycoreio/github-actions-magento2/cache-magento@main
      with:
        mode: 'extension'
        composer_cache_key: ${{ inputs.magento_version }}
    
    - run: composer config repositories.local path ${{ inputs.source_folder }}
      name: Add Github Repo for Testing
      working-directory: ${{ steps.setup-magento.outputs.path }}
      shell: bash
      if: ${{ inputs.use_local_source == 'true' }}

    - run: composer require ${{ inputs.package_name }} "@dev"
      name: Attempt install
      working-directory: ${{ steps.setup-magento.outputs.path }}
      shell: bash
      env:
        COMPOSER_AUTH: ${{ inputs.composer_auth }}

branding:
  icon: "code"
  color: "green"
