name: Test Actions

on:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/_internal-supported-version.yaml"
    - "supported-version/**"
    - "!(**/*.md)"
  pull_request:
    branches:
    - main
    paths:
    - ".github/workflows/_internal-supported-version.yaml"
    - "supported-version/**"
    - "!(**/*.md)"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - run: npm ci
      shell: bash

    - run: npm test
      shell: bash