name: Installation Test

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - "_test/demo-package/**"
    - "installation-test/**"
    - ".github/workflows/_internal-install.yaml"
    - "supported-version/**"
    - "!(**/*.md)"
  pull_request:
    branches:
    - main
    paths:
    - "_test/demo-package/**"
    - "installation-test/**"
    - ".github/workflows/_internal-install.yaml"
    - "supported-version/**"
    - "!(**/*.md)"

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./supported-version
        id: supported-version
      - run: echo ${{ steps.supported-version.outputs.matrix }}

  install-test:
    needs: compute_matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute_matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./installation-test
      with:
        composer_version: ${{ matrix.composer }}
        php_version: ${{ matrix.php }}
        magento_version: ${{ matrix.magento }}
        package_name: graycore/magento2-demo-package
        source_folder: $GITHUB_WORKSPACE/_test/demo-package