name: Init Magento Test

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - "init-magento/**"
    - ".github/workflows/_internal_init_magento.yaml"
    - "supported-version/**"
    - "!(**/*.md)"
  pull_request:
    branches:
    - main
    paths:
    - "init-magento/**"
    - ".github/workflows/_internal_init_magento.yaml"
    - "supported-version/**"
    - "!(**/*.md)"

env:
  magento_folder: ../magento2

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./supported-version
        with:
          kind: all
        id: supported-version
      - run: echo ${{ steps.supported-version.outputs.matrix }}

  init-test:
    needs: compute_matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute_matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v${{ matrix.composer }}
        coverage: none

    - run: composer create-project --repository-url="https://mirror.mage-os.org" "${{ matrix.magento }}" ${{ env.magento_folder }} --no-install
      shell: bash
      name: Create Magento ${{ matrix.magento }} Project 

    - uses: ./init-magento
      name: Init Magento
      with:
        magento_directory: ${{ env.magento_folder }}

    - run: composer install
      shell: bash
      working-directory: ${{ env.magento_folder }}
