name: Unit Test

on:
  push:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - README.md
  pull_request:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - README.md

jobs:
  install-test:
    strategy:
      matrix:
        php_version:
          - 7.4
          - 8.1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./unit-test
      with:
        php_version: ${{ matrix.php_version }}